[package]
name = "hello_android"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.92"
publish = false

# `unsafe_code` is required for `#[no_mangle]`, disable workspace lints to workaround lint error.
# [lints]
# workspace = true

[lib]
# cdylib is required for Android, lib is required for desktop
crate-type = ["cdylib", "lib"]


[dependencies]
eframe = { workspace = true, default-features = false, features = [
  "default_fonts",
  "glow",
  "android-native-activity",
] }
egui_demo_lib = { workspace = true, features = ["chrono"] }

# For image support:
egui_extras = { workspace = true, features = ["default", "image"] }

android_logger.workspace = true
log.workspace = true
winit.workspace = true

[package.metadata.android]
build_targets = ["armv7-linux-androideabi", "aarch64-linux-android"]

[package.metadata.android.sdk]
min_sdk_version = 23
target_sdk_version = 35
