[package]
name = "hello_world_par"
version = "0.1.0"
authors = ["Maxim Osipenko <maxim1999max@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.70"
publish = false


[dependencies]
eframe = { path = "../../crates/eframe", default-features = false, features = [
    # accesskit struggles with threading
    "default_fonts",
    "wgpu",
] }
env_logger = "0.10"
