[package]
name = "egui"
version = "0.7.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Simple, portable immediate mode GUI library for Rust"
edition = "2018"
homepage = "https://github.com/emilk/egui"
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/emilk/egui"
categories = ["gui", "graphics"]
keywords = ["gui", "imgui", "immediate", "portable", "gamedev"]
include = [
  "**/*.rs",
  "Cargo.toml",
]

[lib]

[dependencies]
epaint = { path = "../epaint", default-features = false }
serde = { version = "1", features = ["derive", "rc"], optional = true }

[features]
default = ["default_fonts", "single_threaded"]
persistence = ["serde", "epaint/persistence"]

# If set, egui will use `include_bytes!` to bundle some fonts.
# If you plan on specifying your own fonts you may disable this feature.
default_fonts = ["epaint/default_fonts"]

# Only needed if you plan to use the same egui::Context from multiple threads.
single_threaded = ["epaint/single_threaded"]
multi_threaded = ["epaint/multi_threaded"]
