[package]
name = "egui_demo_lib"
version = "0.13.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Example library for egui"
edition = "2018"
homepage = "https://github.com/emilk/egui"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/emilk/egui"
categories = ["gui", "graphics"]
keywords = ["glium", "egui", "gui", "gamedev"]
include = [
  "../LICENSE-APACHE",
  "../LICENSE-MIT",
  "**/*.rs",
  "Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[lib]

[dependencies]
egui = { version = "0.13.0", path = "../egui", default-features = false }
epi = { version = "0.13.0", path = "../epi" }
unicode_names2 = { version = "0.4.0", default-features = false }

# feature "http":
image = { version = "0.23", default-features = false, features = ["jpeg", "png"], optional = true }

# feature "syntax_highlighting":
syntect = { version = "4", default-features = false, features = ["default-fancy"], optional = true }

# feature "persistence":
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
criterion = { version = "0.3", default-features = false }

[features]
default = []
http = ["image", "epi/http"]
persistence = ["egui/persistence", "epi/persistence", "serde"]
syntax_highlighting = ["syntect"]

# Enable additional checks if debug assertions are enabled (debug builds).
extra_debug_asserts = ["egui/extra_debug_asserts"]
# Always enable additional checks.
extra_asserts = ["egui/extra_asserts"]

[[bench]]
name = "benchmark"
harness = false
