[package]
name = "egui_demo_lib"
version = "0.17.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Example library for egui"
edition = "2021"
rust-version = "1.56"
homepage = "https://github.com/emilk/egui/tree/master/egui_demo_lib"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/emilk/egui/tree/master/egui_demo_lib"
categories = ["gui", "graphics"]
keywords = ["glium", "egui", "gui", "gamedev"]
include = [
  "../LICENSE-APACHE",
  "../LICENSE-MIT",
  "**/*.rs",
  "Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[lib]


[features]
default = ["chrono"]

# Enable additional checks if debug assertions are enabled (debug builds).
extra_debug_asserts = ["egui/extra_debug_asserts"]
# Always enable additional checks.
extra_asserts = ["egui/extra_asserts"]

http = ["egui_extras", "ehttp", "image", "poll-promise"]
persistence = ["egui/persistence", "epi/persistence", "serde"]
serialize = ["egui/serialize",  "serde"]
syntax_highlighting = ["syntect"]


[dependencies]
egui = { version = "0.17.0", path = "../egui", default-features = false }
epi = { version = "0.17.0", path = "../epi" }

chrono = { version = "0.4", features = ["js-sys", "wasmbind"], optional = true }
enum-map = { version = "2", features = ["serde"] }
unicode_names2 = { version = "0.5.0", default-features = false }

# feature "http":
egui_extras = { version = "0.17.0", path = "../egui_extras", features = ["image"], optional = true }
ehttp = { version = "0.2.0", optional = true }
image = { version = "0.24", default-features = false, features = ["jpeg", "png"], optional = true }
poll-promise = { version = "0.1", default-features = false, optional = true }

# feature "syntax_highlighting":
syntect = { version = "4", default-features = false, features = ["default-fancy"], optional = true }

# feature "persistence":
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
criterion = { version = "0.3", default-features = false }


[[bench]]
name = "benchmark"
harness = false
