[package]
name = "images"
version = "0.1.0"
authors = ["Jan Proch√°zka <github.com/jprochazk>"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.92"
publish = false

[lints]
workspace = true


[package.metadata.cargo-machete]
ignored = ["image"] # We only use the dependency to add more features to it


[dependencies]
eframe = { workspace = true, features = [
  "default",
  "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }
egui_extras = { workspace = true, features = ["default", "all_loaders"] }
env_logger = { workspace = true, features = ["auto-color", "humantime"] }
image = { workspace = true, features = ["jpeg", "png"] }
