[package]
name = "emath"
version = "0.8.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Minimal 2D math library for GUI work"
edition = "2018"
homepage = "https://github.com/emilk/egui"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/emilk/egui"
categories = ["mathematics", "gui"]
keywords = ["math", "gui"]
include = [
  "**/*.rs",
  "Cargo.toml",
]

[lib]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
