[package]
name = "egui_glium"
version = "0.5.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Bindings for using Egui natively using the glium library"
edition = "2018"
homepage = "https://github.com/emilk/egui"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/emilk/egui"
categories = ["gui", "graphics"]
keywords = ["glium", "egui", "gui", "gamedev"]
include = [ "**/*.rs", "Cargo.toml"]

[dependencies]
chrono = { version = "0.4" }
clipboard = "0.5"
directories-next = "2"
egui = { version = "0.5.0", path = "../egui", features = ["serde", "serde_json"] }
glium = "0.29"
serde = "1"
serde_json = "1"
webbrowser = "0.5"
