[package]
name = "epi"
version = "0.9.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Backend-agnostic interface for writing apps using egui"
edition = "2018"
homepage = "https://github.com/emilk/egui"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/emilk/egui"
categories = ["gui", "game-development"]
keywords = ["egui", "gui", "gamedev"]
include = [ "**/*.rs", "Cargo.toml"]

[lib]

[dependencies]
egui = { version = "0.9.0", path = "../egui" }
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }

[features]
default = []
http = []
persistence = ["serde", "serde_json"]
