[package]
name = "custom_font_style"
version = "0.1.0"
authors = ["tami5 <kkharji@proton.me>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
publish = false


[dependencies]
eframe = { path = "../../crates/eframe" }
