[package]
name = "egui_web"
version = "0.10.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Bindings for compiling egui code to WASM for a web page"
license = "MIT OR Apache-2.0"
edition = "2018"
homepage = "https://github.com/emilk/egui"
readme = "README.md"
repository = "https://github.com/emilk/egui"
categories = ["gui", "web-programming"]
keywords = ["wasm", "web", "egui", "gui", "gamedev"]
include = [
  "../LICENSE-APACHE",
  "../LICENSE-MIT",
  "**/*.rs",
  "Cargo.toml",
  "src/shader/*.glsl",
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
egui = { version = "0.10.0", path = "../egui" }
epi = { version = "0.10.0", path = "../epi" }
js-sys = "0.3"
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
tts = { version = "0.14", optional = true } # feature screen_reader
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[features]
default = []
http = [
  "epi/http",
  "web-sys/Headers",
  "web-sys/Request",
  "web-sys/RequestInit",
  "web-sys/RequestMode",
  "web-sys/Response",
]
persistence = ["serde", "serde_json"]
screen_reader = ["tts"] # experimental

[dependencies.web-sys]
version = "0.3"
features = [
  "Clipboard",
  "ClipboardEvent",
  "console",
  "CompositionEvent",
  "CssStyleDeclaration",
  "DataTransfer",
  "Document",
  "DomRect",
  "Element",
  "Event",
  "EventListener", 
  "EventTarget",
  "FocusEvent",
  "HtmlCanvasElement",
  "HtmlElement",
  "HtmlInputElement",
  "InputEvent",
  "KeyboardEvent",
  "Location",
  "MouseEvent",
  "Navigator",
  "Performance",
  "Storage",
  "Touch",
  "TouchEvent",
  "TouchList",
  "WebGl2RenderingContext",
  "WebGlBuffer",
  "WebGlProgram",
  "WebGlRenderingContext",
  "WebGlShader",
  "WebGlTexture",
  "WebGlUniformLocation",
  "WheelEvent",
  "Window",
]
