name: Deploy web demo

on:
  # We only run this on merges to main
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types: ["published"]

permissions:
  contents: write # for committing to gh-pages branch

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  # Single deploy job since we're just deploying
  deploy:
    name: Deploy web demo
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: 1.92.0
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "web-demo-"

      - name: Install wasm-opt
        uses: sigoden/install-binary@v1
        with:
          repo: WebAssembly/binaryen
          tag: version_123
          name: wasm-opt

      - run: |
          scripts/build_demo_web.sh --release

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web_demo
          # this option will not maintain any history of your previous pages deployment
          # set to false if you want all page build to be committed to your gh-pages branch history
          single-commit: true
