name: Typos
on: [pull_request]

jobs:
  typos:
    # https://github.com/crate-ci/typos
    # Add exceptions to .typos.toml
    # install and run locally: cargo install typos-cli && typos
    name: typos
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Check spelling of entire workspace
        uses: crate-ci/typos@v1.38.0
